name: flutter_tts
description: A flutter plugin for Text to Speech
version: 0.0.6
author: Daniel Lutton <eyedea32@gmail.com>
homepage: https://github.com/dlutton/flutter_tts

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.eyedeadevelopers.fluttertts
    pluginClass: FlutterTtsPlugin

environment:
  sdk: ">=1.8.0 <=2.0.0"